### ISSUE TITLE
Add Toggle to PasswordField to view password in plain text

### ISSUE THREAD

**Issue by Skidragon** [Qortal/chrome-extension#2]
![image](https://github.com/Qortal/chrome-extension/assets/18124536/3cfe0a10-96b8-4691-acdb-d113363b9144)

Draft Steps to add this feature:

1. Create a PasswordField Component in the components folder using the already written code.
2. Add two necessary icons to indicate whether the password is showing in plain text or not.
3. Change attribute type from password to text and vise-versa to make the password show up in plain text or not.
4. Add the PasswordField in all places where its applicable.
5. Must be accessible, customizable, and tested.

**Comment by JustinReact** [comment]
Looks good :)
