### ISSUE TITLE
Bug: Error when entering password for the second time

### ISSUE THREAD

**Issue by Skidragon** [Qortal/chrome-extension#4]
Reference
[Bug Link](https://github.com/orgs/Qortal/projects/7/views/2?pane=issue&itemId=69654010)

Investigation Findings:
On the UI side it looks fine. I don't know how to trigger the UI part of the app easily. However I will describe what I believe is the problem.

![image](https://github.com/Qortal/chrome-extension/assets/18124536/152d63ec-dfb7-4bbb-9121-da1605e951aa)

Its the part where background.ts may be having issues where I present
sendResponse here is not in scope and not getting set to pendingResponses:
![image](https://github.com/Qortal/chrome-extension/assets/18124536/9c0be1dd-c485-449d-bdbc-0650636caad8)

originalSendResponse key may be fine but value may be bad since sendResponse may be turning out undefined or something, so as a result originalSendResponse may be failing. Another thing which I'm not sure is whether pendingResponses may need to delete on both true and false conditions of isDecline?
![image](https://github.com/Qortal/chrome-extension/assets/18124536/d30db4a4-d73f-4de4-b0de-a15348c76a4b)

**Comment by Philreact** [comment]
thanks for the insights - it helped me fix the bug. The issue was that on the first try the originalResponse was getting deleted. so I moved the pendingResources.delete

**Comment by Skidragon** [comment]
@Philreact awesome, I'll close this issue and PR and start on the other small issues today.
